import type { Project } from "./types";

export const PDF_PROJECTS: Project[] = [
  {
    id: "ai-curated-search-engine",
    title: "AI-Curated Search Engine",
    category: "AI Search Pipeline",
    description: "A restartable discovery pipeline that crawls selected sites, rejects noise, uses local Gemma inference to curate and explain results, and serves ranked article search through FastAPI and React.",
    roles: ["Backend Engineering", "AI Pipeline Design", "Search Engineering"],
    year: "2026",
    technologies: ["Python", "Scrapy", "Ollama / Gemma 3", "MongoDB", "OpenSearch", "FastAPI", "React"],
    accentColor: "emerald",
    imageUrl: "/project-photos/ai-search-stack.jpg",
    hoverImageUrl: "/project-photos/ai-search-usecase.jpg",
    pdfUrl: "/01_AI_Curated_Search_Engine.pdf",
    associatedWith: "GDSC IIT Roorkee",
    contributors: ["Sidheshwar Sarangal"],
    status: "Implemented prototype",
    links: { github: "https://github.com/SidheshwarSarangal/Search-Engin-New" },
    details: {
      problem: "Readers need a focused way to discover thoughtful articles without manually filtering noisy crawled pages or waiting for expensive model inference during every search.",
      solution: "Separated offline collection from the online search path: cheap rules screen URLs first, local Gemma inference classifies and summarizes plausible pages, MongoDB stores curated records, and OpenSearch powers ranked queries exposed by FastAPI.",
      outcomes: [
        "Built a restartable crawl and AI-classification pipeline that persists URL decisions after every page",
        "Kept MongoDB as the curated source of record and OpenSearch as the read-optimized index",
        "Returned explainable summaries and selection reasons with original-publisher links",
      ],
      technologyRoles: [
        { technology: "Scrapy + Python", purpose: "Discover pages from bounded seed sites and apply inexpensive URL/content rejection before AI processing." },
        { technology: "Ollama / Gemma 3", purpose: "Classify relevance locally and generate the summary and selection reason stored with accepted pages." },
        { technology: "MongoDB + OpenSearch", purpose: "Keep durable curated records in MongoDB while serving weighted, read-optimized queries from OpenSearch." },
        { technology: "FastAPI + React", purpose: "Expose ranked JSON results and provide the reader-facing search and pagination experience." },
      ],
      architecture: ["Seed sites", "Scrapy crawler", "Fast screening", "Gemma curation", "MongoDB", "OpenSearch", "FastAPI + React"],
      highlights: ["Local inference", "Resumable processing", "Multi-field ranking", "Original-source attribution"],
    },
    featured: true,
  },
  {
    id: "gmail-query-engine",
    title: "Gmail Query Engine",
    category: "TypeScript Integration Library",
    description: "A stateless TypeScript library for validated Gmail searches, bounded message fetching, MIME decoding, safe link extraction, and explicit label or compose operations.",
    roles: ["Library Engineering", "API Contract Design", "Reliability"],
    year: "2026",
    technologies: ["TypeScript", "Node.js", "Gmail API", "googleapis", "Zod", "MIME", "ESM", "Automated Tests"],
    accentColor: "red",
    imageUrl: "/project-photos/gmail-stack.jpg",
    hoverImageUrl: "/project-photos/gmail-usecase.jpg",
    pdfUrl: "/02_Gmail_Query_Engine.pdf",
    associatedWith: "Reusable backend component",
    contributors: ["Sidheshwar Sarangal"],
    status: "Implemented library",
    links: { github: "https://github.com/SidheshwarSarangal/gmail-query-engine" },
    details: {
      problem: "Applications integrating Gmail need stable typed contracts, safe MIME handling, predictable resource limits, and mutation behavior that does not hide ambiguous outcomes.",
      solution: "Placed schema validation and a public engine facade in front of a replaceable Gmail adapter, normalized vendor resources into stable results, bounded concurrency and body sizes, and kept credentials under host ownership.",
      outcomes: [
        "Supported raw Gmail syntax and structured query construction with pagination",
        "Decoded nested multipart bodies and extracted links while excluding unsafe schemes",
        "Separated safely retryable reads from one-shot mutations and tested through a fake Gmail client",
      ],
      technologyRoles: [
        { technology: "TypeScript + Zod", purpose: "Define stable public contracts and reject invalid commands, authentication shapes, and operational limits early." },
        { technology: "Gmail API + googleapis", purpose: "Execute caller-authorized searches, message reads, label changes, drafts, and sends behind a replaceable adapter." },
        { technology: "MIME + base64url", purpose: "Normalize nested message bodies, attachment metadata, and safe links into a predictable result shape." },
        { technology: "Automated tests", purpose: "Exercise engine behavior through a fake Gmail client without requiring real accounts or credentials in CI." },
      ],
      architecture: ["Host auth", "Zod validation", "Engine facade", "Gmail adapter", "MIME normalizer", "Safe actions", "Stable result"],
      highlights: ["No token persistence", "Bounded concurrency", "Structured errors", "Credential-free tests"],
    },
    featured: true,
  },
  {
    id: "nodrica-workflow-engine",
    title: "Nodrica Workflow Engine",
    category: "Workflow Orchestration",
    description: "A domain-neutral TypeScript engine that validates serializable DAG workflows before executing deterministic routes with retries, timeouts, cancellation, fallback edges, and lifecycle events.",
    roles: ["Systems Design", "TypeScript Engineering", "Test Design"],
    year: "2026",
    technologies: ["TypeScript", "Directed Acyclic Graphs", "Async Handlers", "AbortSignal", "Retries / Backoff", "Unit Tests"],
    accentColor: "purple",
    imageUrl: "/project-photos/nodrica-stack.jpg",
    hoverImageUrl: "/project-photos/nodrica-usecase.jpg",
    pdfUrl: "/03_Nodrica_Workflow_Engine.pdf",
    associatedWith: "Reusable orchestration package",
    contributors: ["Sidheshwar Sarangal"],
    status: "Implemented TypeScript package",
    links: { github: "https://github.com/SidheshwarSarangal/nodrica" },
    details: {
      problem: "Node-based automation becomes difficult to audit when graph rules, branching, retry behavior, and failure paths are implicit or defined as arbitrary runtime functions.",
      solution: "Designed a serializable workflow contract with validation-before-execution, registered node handlers, declaration-ordered conditions, a single explicit fallback, bounded retries, timeouts, cancellation, and immutable result capture.",
      outcomes: [
        "Rejected cycles, missing nodes, disconnected graphs, and ambiguous routing before any handler ran",
        "Made success and failure routing deterministic and explainable",
        "Kept observability callbacks isolated so they cannot alter workflow outcomes",
      ],
      technologyRoles: [
        { technology: "TypeScript contracts", purpose: "Keep flow definitions, conditions, node configuration, errors, and results serializable and inspectable." },
        { technology: "DAG validation", purpose: "Reject cycles, disconnected nodes, missing identities, and unsafe routing policies before execution begins." },
        { technology: "Async handlers + AbortSignal", purpose: "Run host-provided behavior with cancellation, per-attempt timeouts, and attempt metadata." },
        { technology: "Retries + lifecycle events", purpose: "Apply explicit bounded recovery policies and emit observability events without allowing callbacks to change results." },
      ],
      architecture: ["Flow definition", "Graph validator", "Node registry", "Deterministic executor", "Retry / timeout", "Events", "Serializable result"],
      highlights: ["Connected DAG contract", "Explicit failure edges", "AbortSignal support", "Domain-neutral core"],
    },
    featured: true,
  },
  {
    id: "ai-translation-image-platform",
    title: "AI Translation & Image Platform",
    category: "Multimodal AI Product",
    description: "A subscription-gated full-stack demonstration combining email OTP, sandbox plans, text translation, voice translation and playback, and AI image interpretation under one account.",
    roles: ["Full-Stack Development", "AI Integration", "Product Prototyping"],
    year: "2025",
    technologies: ["Angular", "Node.js / Express", "MongoDB", "Groq AI", "Cloudinary", "Cashfree Sandbox", "JWT", "Email OTP"],
    accentColor: "purple",
    imageUrl: "/project-photos/ai-translation-stack.jpg",
    hoverImageUrl: "/project-photos/ai-translation-usecase.jpg",
    pdfUrl: "/04_AI_Translation_Image_Platform.pdf",
    associatedWith: "Suhane Safar",
    contributors: ["Sidheshwar Sarangal", "Product team"],
    startedAt: "Mar 2025",
    completedAt: "May 2025",
    status: "Demo application · sandbox payments",
    links: { github: "https://github.com/SidheshwarSarangal/cashfree-ai-new-final" },
    details: {
      problem: "An internal technology exploration needed to evaluate authenticated multimodal AI features and subscription journeys together rather than as isolated API demos.",
      solution: "Built an Angular experience backed by Express and MongoDB, connected email verification and Cashfree Sandbox access state, and normalized Groq text, speech, and vision workflows with Cloudinary-assisted image handling.",
      outcomes: [
        "Connected signup, OTP verification, plan selection, sandbox payment, and gated AI access",
        "Delivered separate text, audio, and image experiences sharing one authenticated account state",
        "Documented authorization, webhook-verification, expiry, testing, and cleanup gaps candidly",
      ],
      technologyRoles: [
        { technology: "Angular", purpose: "Deliver account, plan, text translation, speech, playback, and image-analysis interfaces." },
        { technology: "Express + MongoDB", purpose: "Coordinate authentication, subscription state, uploads, AI requests, and persistent user records." },
        { technology: "Groq AI + Cloudinary", purpose: "Process language, speech, and vision inputs, using hosted media URLs for image interpretation." },
        { technology: "Cashfree Sandbox + OTP", purpose: "Demonstrate email verification, plan selection, payment authorization, and gated feature access." },
      ],
      architecture: ["Angular client", "OTP + plan access", "Express API", "Cloudinary media", "Groq AI", "MongoDB", "Normalized response"],
      highlights: ["Three AI modalities", "Sandbox subscription flow", "Media normalization", "Explicit production gaps"],
    },
    featured: true,
  },
  {
    id: "collaborative-whiteboard",
    title: "Real-Time Collaborative Whiteboard",
    category: "Realtime Collaboration",
    description: "A MERN whiteboard with shared rooms, low-latency Socket.IO drawing, persistent strokes, public or password-controlled access, rich canvas tools, exports, and a Kubernetes architecture variant.",
    roles: ["Full-Stack Development", "Realtime Systems", "Deployment Architecture"],
    year: "2025",
    technologies: ["React + Vite", "Express", "Socket.IO", "MongoDB", "JWT", "Canvas", "Kubernetes", "Kind"],
    accentColor: "cyan",
    imageUrl: "/project-photos/whiteboard-stack.jpg",
    hoverImageUrl: "/project-photos/whiteboard-usecase.jpg",
    pdfUrl: "/05_Real_Time_Collaborative_Whiteboard.pdf",
    associatedWith: "MARS · IIT Roorkee",
    contributors: ["Sidheshwar Sarangal", "Project collaborators"],
    status: "Implemented full-stack prototype",
    links: { github: "https://github.com/SidheshwarSarangal/whiteBoard" },
    details: {
      problem: "Collaborative drawing requires room-scoped realtime delivery, durable board state, access decisions, editing tools, and export without coupling every gesture to slow persistence calls.",
      solution: "Separated immediate Socket.IO drawing events from durable REST resources and MongoDB state, used room IDs as the collaboration boundary, and explored both a monolithic deployment and service separation behind Kubernetes ingress.",
      outcomes: [
        "Broadcast live drawing updates only to participants in the active room",
        "Persisted board data for later visits while supporting public and private room access",
        "Added pen, eraser, text, shapes, styling, undo/redo, and PNG/JPG/PDF export",
      ],
      technologyRoles: [
        { technology: "React + Canvas", purpose: "Provide room dashboards, drawing tools, local rendering, styling, undo/redo, and export controls." },
        { technology: "Socket.IO", purpose: "Broadcast low-latency drawing events only to participants connected to the same room." },
        { technology: "Express + MongoDB", purpose: "Manage accounts, room metadata, permissions, messages, and durable saved drawing state." },
        { technology: "Kubernetes + Kind", purpose: "Explore separating account, room, drawing, realtime, and user responsibilities behind local ingress." },
      ],
      architecture: ["Canvas clients", "Room access", "Socket.IO", "Express REST API", "MongoDB", "Export layer", "Kubernetes variant"],
      highlights: ["Room-scoped events", "Persistent strokes", "Permission modes", "Monolith vs services"],
    },
    featured: true,
  },
  {
    id: "full-stack-social-platform",
    title: "Full-Stack Social Media Platform",
    category: "MERN Social Product",
    description: "A MERN social platform with OTP signup, JWT login, profiles, discovery, follows, posts, reels, expiring stories, notifications, Cloudinary media, and persistent Socket.IO messaging.",
    roles: ["Full-Stack Development", "Authentication", "Realtime Messaging"],
    year: "2024",
    technologies: ["React", "Redux Toolkit", "Tailwind CSS", "Express", "MongoDB", "Cloudinary", "Socket.IO", "JWT"],
    accentColor: "red",
    imageUrl: "/project-photos/social-platform-stack.jpg",
    hoverImageUrl: "/project-photos/social-platform-usecase.jpg",
    pdfUrl: "/06_Full_Stack_Social_Media_Platform%20(1).pdf",
    associatedWith: "ACM IIT Roorkee",
    contributors: ["Sidheshwar Sarangal"],
    status: "Implemented prototype",
    links: { github: "https://github.com/SidheshwarSarangal/social-media-website" },
    details: {
      problem: "A multimedia social product must coordinate identity, relationship rules, several content lifecycles, media hosting, notifications, and both live and persistent conversation state.",
      solution: "Connected React and Redux experiences to JWT-protected Express routes and Mongoose models, stored media through Cloudinary, modeled posts/reels/stories separately, and paired saved chat history with Socket.IO delivery.",
      outcomes: [
        "Implemented OTP signup, profiles, prefix search, follow flows, and notifications",
        "Supported image posts, short-video reels, and 24-hour stories as distinct content types",
        "Combined MongoDB message persistence with room-based live delivery",
      ],
      technologyRoles: [
        { technology: "React + Redux Toolkit", purpose: "Manage protected experiences and shared state for identity, feeds, profiles, discovery, and messaging." },
        { technology: "Express + JWT", purpose: "Route authenticated social operations through feature controllers and identity middleware." },
        { technology: "MongoDB + Cloudinary", purpose: "Persist users, relationships, content metadata, and chats while hosting image and video binaries externally." },
        { technology: "Socket.IO", purpose: "Deliver messages to active conversation rooms while MongoDB preserves conversation history." },
      ],
      architecture: ["React + Redux", "JWT middleware", "Express controllers", "Cloudinary media", "Mongoose models", "Socket.IO chat", "Client updates"],
      highlights: ["Multiple media lifecycles", "Social graph", "Persistent realtime chat", "Protected routes"],
    },
    featured: true,
  },
  {
    id: "jpmorgan-midas-simulation",
    title: "JPMorgan Midas Transaction Simulation",
    category: "Event-Driven Java Backend",
    description: "A Spring Boot training simulation that consumes Kafka transactions, validates and enriches them through an incentive API, persists outcomes, updates balances, and exposes REST reads.",
    roles: ["Backend Engineering", "Event Processing", "Integration Testing"],
    year: "2025",
    technologies: ["Java 17", "Spring Boot", "Apache Kafka", "Spring Data JPA", "H2", "RestTemplate", "Maven", "Embedded Kafka"],
    accentColor: "blue",
    imageUrl: "/project-photos/midas-stack.jpg",
    hoverImageUrl: "/project-photos/midas-usecase.jpg",
    pdfUrl: "/07_JPMorgan_Midas_Transaction_Processing.pdf",
    associatedWith: "JPMorgan Chase & Co. · Forage",
    contributors: ["Sidheshwar Sarangal"],
    status: "Completed Forage simulation",
    links: { github: "https://github.com/SidheshwarSarangal/forage-midas" },
    details: {
      problem: "A transaction-processing exercise needed to demonstrate reliable event intake, validation, persistence, external service integration, balance updates, and an independently queryable read path.",
      solution: "Used Kafka for ingestion, Spring domain services for validation, RestTemplate for incentive enrichment, JPA/H2 for repeatable persistence, and a REST controller for balance reads, verified with embedded infrastructure and debugging.",
      outcomes: [
        "Consumed deserialized transaction messages from a configurable Kafka topic",
        "Persisted enriched transaction entities and applied verified balance changes",
        "Tested messaging and storage locally with Embedded Kafka, H2, Maven, and debugger inspection",
      ],
      technologyRoles: [
        { technology: "Apache Kafka", purpose: "Carry serialized transaction events into the service through a configurable topic." },
        { technology: "Spring Boot", purpose: "Consume events, validate domain constraints, coordinate incentive enrichment, and apply transaction effects." },
        { technology: "JPA + H2", purpose: "Persist transaction and user entities in a repeatable local environment used by the simulation tests." },
        { technology: "RestTemplate + REST", purpose: "Call the external incentive service and expose an independent JSON endpoint for balance reads." },
      ],
      architecture: ["Kafka topic", "Spring consumer", "Validation", "Incentive REST API", "JPA + H2", "Balance update", "REST query"],
      highlights: ["Event-driven flow", "External enrichment", "Repeatable local tests", "Training-simulation scope"],
    },
    featured: true,
  },
  {
    id: "department-library-system",
    title: "Department Library Management System",
    category: "Role-Based MERN Application",
    description: "A departmental library application for book discovery, cart-based requests, administrator checkout, borrowed-item tracking, explicit return states, feedback, bulk import, and role-specific interfaces.",
    roles: ["Full-Stack Development", "Workflow Design", "Data Modeling"],
    year: "2025",
    technologies: ["React", "Node.js / Express", "MongoDB / Mongoose", "Passport", "bcrypt", "REST APIs", "Role-Based UI", "bulkWrite"],
    accentColor: "amber",
    imageUrl: "/project-photos/library-stack.jpg",
    hoverImageUrl: "/project-photos/library-usecase.jpg",
    pdfUrl: "/08_Department_Library_Management_System.pdf",
    associatedWith: "BSBE Department · IIT Roorkee",
    contributors: ["Sidheshwar Sarangal", "Department collaborators"],
    status: "Implemented MERN application",
    links: { github: "https://github.com/SidheshwarSarangal/department-vikram-project" },
    details: {
      problem: "Students and librarians needed one workflow for discovery, approval-based issue, borrowed-item tracking, returns, catalogue administration, and feedback rather than disconnected manual records.",
      solution: "Built role-specific React experiences over Express controllers and Mongoose models, staged requests in a cart before administrator checkout, modeled returning status explicitly, and added ISBN-based bulk upserts.",
      outcomes: [
        "Supported multi-field book search, cart requests, administrator checkout, and borrowed lists",
        "Created an explicit student-request and administrator-completion return workflow",
        "Added profile, feedback-state, user-management, and bulk catalogue operations",
      ],
      technologyRoles: [
        { technology: "React", purpose: "Provide distinct student and administrator journeys for discovery, requests, borrowing, returns, feedback, and management." },
        { technology: "Express controllers", purpose: "Own user, book, cart, checkout, return, search, filtering, and feedback operations." },
        { technology: "MongoDB / Mongoose", purpose: "Store catalogue records, users, carts, borrowed states, activity, and feedback workflow data." },
        { technology: "Passport + bcrypt", purpose: "Maintain authenticated sessions and protect stored account passwords through hashing." },
      ],
      architecture: ["Student / admin UI", "Express routes", "User controller", "Book controller", "Feedback controller", "MongoDB models", "Approval states"],
      highlights: ["Role-based journeys", "Approval staging", "Return state machine", "ISBN bulk upserts"],
    },
    featured: true,
  },
  {
    id: "public-x-feed-viewer",
    title: "Public X Feed Viewer Prototype",
    category: "Browser Extension + FastAPI",
    description: "An academic browser-extension prototype that selects an available alternate feed, resolves stored session material through FastAPI and MongoDB, normalizes timeline media, and handles expiry explicitly.",
    roles: ["Extension Development", "Python Backend", "Security Review"],
    year: "2024",
    technologies: ["Chrome Extension", "JavaScript / React", "Python", "FastAPI", "Twikit", "MongoDB", "Browser Storage", "Sessions"],
    accentColor: "cyan",
    imageUrl: "/project-photos/x-feed-stack.jpg",
    hoverImageUrl: "/project-photos/x-feed-usecase.jpg",
    pdfUrl: "/09_Public_Twitter_X_Feed_Viewer.pdf",
    associatedWith: "GDSC IIT Roorkee",
    contributors: ["Sidheshwar Sarangal"],
    status: "Implemented academic prototype",
    links: { github: "https://github.com/SidheshwarSarangal/X_feed_extension" },
    details: {
      problem: "The prototype explored switching between consented representations of public home feeds while preserving timeline media and making invalid session state recoverable.",
      solution: "Separated extension interaction from Python login/session and feed services, associated account references with prototype session records, normalized timeline items, and deleted expired session material before requesting re-authentication.",
      outcomes: [
        "Built extension access, search, selector, and feed-integration experiences",
        "Returned text, image, video, like, and comment metadata through a normalized feed service",
        "Documented why the password/cookie boundary is prototype-only and outlined delegated-access hardening",
      ],
      technologyRoles: [
        { technology: "Chrome Extension", purpose: "Provide access, search, account selection, browser storage, and alternate-feed rendering inside the browser." },
        { technology: "FastAPI + Twikit", purpose: "Implement prototype login/session operations and retrieve normalized timeline content." },
        { technology: "MongoDB", purpose: "Associate account references with prototype session material so a later viewer can resolve an available feed." },
        { technology: "Expiry handling", purpose: "Delete invalid session material and surface a recoverable re-authentication state instead of an empty feed." },
      ],
      architecture: ["Extension popup", "Account selector", "FastAPI services", "Session matching", "MongoDB", "Timeline retrieval", "Expiry recovery"],
      highlights: ["Browser + backend state", "Media normalization", "Explicit expiry", "Security-first redesign path"],
    },
    featured: true,
  },
  {
    id: "investing-accelerator-frontend",
    title: "Investing Accelerator Frontend Architecture",
    category: "Product Design + Next.js",
    description: "A frontend architecture and product-design case study for a stock-learning platform covering discovery, reusable UI, plan selection, checkout handoff, entitlement, cancellation, refund, recovery states, and production debugging.",
    roles: ["Frontend Architecture", "Product Design", "Integration Contracts", "Production Debugging"],
    year: "2026",
    technologies: ["Next.js", "React", "Responsive UI", "Component Architecture", "API Contracts", "Subscription States", "Logs"],
    accentColor: "emerald",
    imageUrl: "/project-photos/investing-stack.jpg",
    hoverImageUrl: "/project-photos/investing-usecase.jpg",
    pdfUrl: "/10_Investing_Accelerator_Product_Design_Frontend%20(1).pdf",
    associatedWith: "Investing Accelerator Summit",
    contributors: ["Sidheshwar Sarangal", "Cross-functional product team"],
    startedAt: "Jan 2026",
    completedAt: "Feb 2026",
    status: "Internship contribution case study",
    links: {},
    details: {
      problem: "A subscription-based learning product needs a coherent interface across content discovery, access, checkout, entitlement, cancellation, refund, and every pending, failed, or recoverable state.",
      solution: "Organized Next.js routes and reusable components, modeled transactional UI states, specified typed API requirements and access guards, and used application logs and data-flow analysis to improve failure recovery without claiming ownership of private payment APIs.",
      outcomes: [
        "Mapped the complete subscription lifecycle rather than treating payment as a single success action",
        "Defined reusable loading, empty, confirmation, status, error, and retry patterns",
        "Supported production issue diagnosis while keeping backend verification and persistence responsibilities explicit",
      ],
      technologyRoles: [
        { technology: "Next.js + React", purpose: "Organize learning, catalogue, dashboard, plans, billing, account, and entitlement-aware page experiences." },
        { technology: "Component architecture", purpose: "Reuse navigation, cards, forms, modals, status banners, tables, skeletons, and responsive primitives." },
        { technology: "Typed API contracts", purpose: "Define frontend requirements for checkout, subscription status, cancellation, refund, and error recovery." },
        { technology: "Logs + data-flow analysis", purpose: "Trace failed production journeys and translate backend outcomes into useful user-visible recovery states." },
      ],
      architecture: ["Next.js routes", "Design system", "Frontend state", "Access guards", "Typed API client", "Backend contracts", "Logs + recovery"],
      highlights: ["Full transactional state model", "Reusable interface patterns", "Clear ownership boundary", "Production diagnostics"],
    },
    featured: true,
  },
];
